[profile.default]
solc_version = '0.8.24'
evm_version = 'shanghai'
optimizer = false
verbosity = 1
fuzz_runs = 5
script = 'scripts'
[profile.optimized]
via_ir = true
optimizer = true
optimizer_runs = 1_000_000_000
[fmt]
line_length = 100
[fuzz]
runs = 4
