[profile.default]
solc_version = '0.8.17'
optimizer_runs = 35_000
verbosity = 1
fuzz_runs = 5
remappings = [
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'
]
[fmt]
line_length = 100
